server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: midas_donation
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/midas
    username: crbpavel
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true

